### ISSUE TITLE
bodega.id, campo.id, vid.id must be autoincremental field with consecutive numbers

### ISSUE THREAD

**Issue by Japoivvb** [carlosbarque/p2viticulture#2]
1. ids generated by Hibernate using corresponding models should be autoincremental to allow insert data in field instruction with an error regarding duplicated query.

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by carlosbarque** [comment]
![issue1](https://github.com/carlosbarque/p2viticulture/assets/148006519/7ee7f8f3-f696-4eda-aeef-fd0b25e01812)

**Comment by carlosbarque** [comment]
![issue2](https://github.com/carlosbarque/p2viticulture/assets/148006519/8700240d-7d9d-4fbd-8ca9-36c55fd9b5b9)
![image](https://github.com/carlosbarque/p2viticulture/assets/148006519/58c4efe3-bb7b-4661-98fa-e8cc6ea12c98)
![image](https://github.com/carlosbarque/p2viticulture/assets/148006519/0906374a-cdc6-4fc9-9d8c-7736bdbdeecf)

Ejemplo de que funcionan bien

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ko, I must close the issue
