### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [carlosbarque/p2viticulture#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by carlosbarque** [comment]
![image](https://github.com/carlosbarque/p2viticulture/assets/148006519/385263a2-10a1-47cf-91ee-c845f852f764)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ko, who opens the issue must close it also
